### ISSUE TITLE
倒數計時 component

### ISSUE THREAD

**Issue by ychi** [ychi/fire-elect#16]
會在不同頁面共用
<img width="89" alt="Screenshot 2020-01-04 at 17 16 48" src="https://user-images.githubusercontent.com/5203395/71768433-34cf2c80-2f16-11ea-9810-b57d5358081b.png">

**Comment by kaichehung** [comment]
如果沒人要認領的話，我切完版會來處理一下

**Comment by yipei1028** [comment]
這個我有領了，已經發一個PR，但有一些畫面不太確定的問題，應該還會再改，所以還沒close
