### ISSUE TITLE
表單填寫

### ISSUE THREAD

**Issue by ichiaohsu** [ychi/fire-elect#35]
- [ ] 隱私條款部分請把連結設在「隱私條款」4個字上而非checkbox上
- [ ] 隱私條款4個字default- 請underline，大家才知道可以外連
- [x] 表單填寫的立委名請存入資料庫

**Comment by ichiaohsu** [comment]
@ychi 勾勾救命，剩的兩個我搞不定

**Comment by imyentsen** [comment]
這個我解了！我用一個 Help Icon 取代直接給連結

**Comment by ychi** [comment]
感謝 @imyentsen
